"""Generates docs/business_insights.md and docs/data_quality.md from the computed outputs.

Every number in these documents is read from the pipeline results at run time,
so the reports always match the data (nothing is hand-typed)."""
from __future__ import annotations

import pandas as pd

from python.config import ANALYSIS_DATE, DOCS_DIR, get_logger

log = get_logger("reporting.report_writer")


def inr(x: float) -> str:
    if abs(x) >= 1e7:
        return f"₹{x / 1e7:,.2f} Cr"
    if abs(x) >= 1e5:
        return f"₹{x / 1e5:,.2f} L"
    return f"₹{x:,.0f}"


def md_table(df: pd.DataFrame, cols: list[str] | None = None, fmt: dict | None = None) -> str:
    d = df[cols] if cols else df
    fmt = fmt or {}
    head = "| " + " | ".join(d.columns) + " |\n|" + "---|" * len(d.columns) + "\n"
    rows = []
    for _, r in d.iterrows():
        rows.append("| " + " | ".join(fmt[c](r[c]) if c in fmt else (("-" if pd.isna(r[c]) else f"{r[c]:,.2f}") if isinstance(r[c], float) else str(r[c]))
                                       for c in d.columns) + " |")
    return head + "\n".join(rows) + "\n"


def write_business_insights(k: dict, stats_out: dict, seg: pd.DataFrame, dq_overall: tuple[float, float]) -> None:
    h = k["headline"]
    yr = k["yearly"]
    cat, reg, ch, prod = k["category"], k["region"], k["channel"], k["product"]
    cat_known = cat[cat["category"] != "Unknown"]
    mo = k["monthly"].copy()
    mo["m"] = mo["year_month"].str[-2:]
    season = mo.groupby("m")["revenue"].mean()
    peak_months = ", ".join(pd.to_datetime(season.nlargest(2).index, format="%m").strftime("%B"))
    best_month = mo.loc[mo["revenue"].idxmax()]
    db = k["discount_band"].set_index("discount_band")
    dr = k["delivery_by_region"].sort_values("on_time_pct")
    rr = k["return_reasons"]
    sc = k["support_category"]
    tests = {t["name"]: t for t in stats_out["tests"]}
    t_disc = tests["Deep discount (>=15%) vs low discount (<15%) - order value"]
    t_ret = tests["Return rate: Marketplace vs Website"]
    t_loy = tests["Loyalty members vs non-members - orders per customer"]
    t_csat = tests["Ticket resolution time vs CSAT"]
    t_ch = tests["Order value across 4 sales channels"]
    segi = seg.set_index("segment")
    top_cat_margin = cat_known.sort_values("profit_margin_pct", ascending=False)
    top_ret_cat = cat_known.sort_values("return_rate_pct", ascending=False).iloc[0]
    bottom10 = prod[prod["product_id"] != "P_UNKNOWN"].tail(10)
    y = yr.set_index("year")

    txt = f"""# Business Insights Report

> **Data disclaimer:** all figures come from the **synthetic** UrbanCart Retail dataset generated by this project
> (fictional company, seed = 42). They demonstrate the analysis workflow. They are not real business results.
> This file is **auto-generated** by `run_pipeline.py` (`python/reporting/report_writer.py`). Snapshot date: {ANALYSIS_DATE}.

## 1. Executive Summary

- **Revenue {inr(h['total_revenue'])}** and **profit {inr(h['total_profit'])}** ({h['profit_margin_pct']:.2f}% margin) from
  **{int(h['total_orders']):,} orders** placed by **{int(h['total_customers']):,} customers**, Jan 2023 to Dec 2025.
- Revenue grew **{y.loc[2024, 'yoy_revenue_growth_pct']:.1f}%** in 2024 and **{y.loc[2025, 'yoy_revenue_growth_pct']:.1f}%** in 2025.
  Margin moved from {y.loc[2023, 'profit_margin_pct']:.2f}% (2023) to {y.loc[2025, 'profit_margin_pct']:.2f}% (2025).
- Average order value is **{inr(h['aov'])}**. {h['repeat_customer_pct']:.1f}% of buyers ordered more than once.
  The top 20% of customers produce **{h['top20pct_customers_revenue_share']:.1f}%** of revenue.
- **{h['return_rate_lines_pct']:.2f}%** of order lines were returned, refunding {inr(h['refund_value'])}
  ({h['refund_pct_of_revenue']:.2f}% of revenue). On-time delivery is {h['on_time_delivery_pct']:.1f}%.
- Raw-data quality score went from **{dq_overall[0]:.2f} to {dq_overall[1]:.2f}** after the cleaning pipeline.

## 2. Sales Insights

{md_table(yr, ['year', 'revenue', 'profit', 'orders', 'aov', 'yoy_revenue_growth_pct', 'profit_margin_pct'], {'revenue': inr, 'profit': inr, 'aov': inr, 'orders': lambda v: f"{int(v):,}", 'year': lambda v: str(int(v))})}
- **Seasonality:** the strongest months on average are **{peak_months}** (festive season). The best single month was
  **{best_month['year_month']}** with {inr(best_month['revenue'])}.
- **Discounts and margin:** orders with no discount earn a {db.loc['0%', 'profit_margin_pct']:.2f}% margin. The 11-20% band earns
  {db.loc['11-20%', 'profit_margin_pct']:.2f}%, and lines above 20% discount earn {db.loc['>20%', 'profit_margin_pct']:.2f}%.
  Deep discounting removes most of the profit.
- **Discount test:** median order value for orders with ≥15% discount is {inr(t_disc['group_a_median'])}, against
  {inr(t_disc['group_b_median'])} for orders under 15% (Mann-Whitney p = {t_disc['p_value_mannwhitney']:.2g}).
  Deep-discount orders are **smaller**, not bigger. This is observational data, so it shows association and does not prove that discounts reduce basket size.

## 3. Customer Insights

{md_table(seg, ['segment', 'customers', 'customer_share_pct', 'revenue_share_pct', 'avg_orders', 'avg_recency_days'])}
- **High Value** customers are {segi.loc['High Value', 'customer_share_pct']:.1f}% of buyers and produce
  {segi.loc['High Value', 'revenue_share_pct']:.1f}% of revenue.
- **At Risk** customers ({int(segi.loc['At Risk', 'customers']):,}) used to buy often or spend a lot. Their last order was
  about {segi.loc['At Risk', 'avg_recency_days']:.0f} days ago on average, and they hold {segi.loc['At Risk', 'revenue_share_pct']:.1f}% of historical revenue.
  This is the largest win-back opportunity.
- **Retention:** on average {h['avg_month1_retention_pct']:.1f}% of a monthly cohort orders again in month 1, and
  {h['avg_month3_retention_pct']:.1f}% in month 3.
- **Loyalty programme:** members average {t_loy['group_a_mean']:.2f} orders against {t_loy['group_b_mean']:.2f} for non-members
  (Mann-Whitney p = {t_loy['p_value']:.2g}). Members may have joined *because* they already shop often (self-selection), so this does not prove causation.

## 4. Product Insights

{md_table(cat_known, ['category', 'revenue', 'revenue_share_pct', 'profit_margin_pct', 'return_rate_pct', 'avg_discount_pct'], {'revenue': inr})}
- **{cat_known.iloc[0]['category']}** is the largest category by revenue ({cat_known.iloc[0]['revenue_share_pct']:.1f}%) with a
  {cat_known.iloc[0]['profit_margin_pct']:.2f}% margin. **{top_cat_margin.iloc[0]['category']}** has the highest margin
  ({top_cat_margin.iloc[0]['profit_margin_pct']:.2f}%).
- **{top_ret_cat['category']}** has the highest return rate ({top_ret_cat['return_rate_pct']:.2f}% of lines).
- The top 20% of products produce {h['top20pct_products_revenue_share']:.1f}% of revenue (long-tail catalogue).
  The 10 weakest products together sold only {inr(bottom10['revenue'].sum())}, making them candidates for range rationalisation.

## 5. Regional & Channel Insights

{md_table(reg, ['region_name', 'revenue', 'revenue_share_pct', 'customers', 'aov', 'profit_margin_pct', 'return_rate_pct'], {'revenue': inr, 'aov': inr})}
{md_table(ch, ['channel_name', 'revenue', 'revenue_share_pct', 'orders', 'aov', 'avg_discount_pct', 'return_rate_pct'], {'revenue': inr, 'aov': inr, 'orders': lambda v: f"{int(v):,}"})}
- **{reg.iloc[0]['region_name']}** is the largest zone ({reg.iloc[0]['revenue_share_pct']:.1f}% of revenue) and
  **{reg.iloc[-1]['region_name']}** the smallest ({reg.iloc[-1]['revenue_share_pct']:.1f}%).
- Order value {'**does** differ statistically' if t_ch['significant'] else 'does **not** differ significantly'} between channels
  (Kruskal-Wallis p = {t_ch['p_value']:.3f}). The AOV gap between channels is small in rupee terms (see table), so it matters little in practice.
- Return rates **do** differ: Marketplace {t_ret['group_a_rate_pct']:.2f}% vs Website {t_ret['group_b_rate_pct']:.2f}%
  (two-proportion z = {t_ret['z']:.1f}, p < 0.001).

## 6. Operations Insights

- **Delivery:** {dr.iloc[0]['region_name']} has the lowest on-time rate ({dr.iloc[0]['on_time_pct']:.1f}%, avg
  {dr.iloc[0]['avg_delivery_days']:.2f} days) against {dr.iloc[-1]['region_name']} at {dr.iloc[-1]['on_time_pct']:.1f}%.
- **Returns:** the top reason is **{rr.iloc[0]['return_reason']}** ({rr.iloc[0]['share_pct']:.1f}% of returns).
  **Defective Product** returns carry the highest refund value ({inr(rr.set_index('return_reason').loc['Defective Product', 'refund'])}).
- **Support:** {int(h['support_tickets']):,} tickets ({h['tickets_per_100_orders']:.2f} per 100 orders). Median resolution is
  {h['median_resolution_hours']:.1f} h, SLA is met on {h['sla_met_pct']:.1f}% of tickets, and average CSAT is {h['avg_csat']:.2f}/5.
  **{sc.sort_values('sla_met_pct').iloc[0]['ticket_category']}** tickets have the worst SLA attainment
  ({sc.sort_values('sla_met_pct').iloc[0]['sla_met_pct']:.1f}%).
- Resolution time and CSAT are negatively correlated (Spearman ρ = {t_csat['rho']:.2f}, p < 0.001): slower fixes go with lower satisfaction.
- {h['cancellation_rate_pct']:.2f}% of orders were cancelled.

## 7. Data Quality Findings

- Overall DQ score: **{dq_overall[0]:.2f} (raw) to {dq_overall[1]:.2f} (clean)**. See [data_quality.md](data_quality.md) for every issue,
  how it was detected and how it was fixed.
- Remaining known gaps: customers without e-mail, an 'Unknown' customer/product member for orphan keys, and
  returns with an impossible date (date nulled, return kept).

## 8. Potential Business Actions (to validate with a controlled test)

1. **Review deep discounts.** Lines above 20% discount earn a {db.loc['>20%', 'profit_margin_pct']:.2f}% margin, against {db.loc['0%', 'profit_margin_pct']:.2f}% at full price. A/B test a lower discount cap in the festive season.
2. **Win back At-Risk customers** with targeted offers. Measure success by the reactivation rate of a randomised holdout.
3. **Fix size/fit returns** in Fashion (size guides, fit reviews). Size/Fit is the top return reason.
4. **Marketplace returns:** audit listing accuracy and seller quality. Marketplace return rate is significantly above Website.
5. **{dr.iloc[0]['region_name']}-zone logistics:** review courier partners. {dr.iloc[0]['region_name']} has the lowest on-time delivery rate.
6. **Support SLA:** add staff to the slowest ticket categories. Faster resolution is strongly associated with higher CSAT.

## 9. Limitations

- The data is **synthetic**. Patterns were simulated, so the findings illustrate method, not market reality.
- All tests are **observational**, not randomised experiments, so they show association, not causation.
- Profit excludes shipping, marketing and overheads (product-level contribution margin only).
- CLV is a simple proxy (annualised revenue × margin × 3-year horizon), not a predictive model.
- Very large samples make tiny differences "significant", so read effect sizes, not only p-values.
"""
    (DOCS_DIR / "business_insights.md").write_text(txt, encoding="utf-8")
    log.info("Wrote docs/business_insights.md")


def write_data_quality(issues: pd.DataFrame, raw_checks: pd.DataFrame, clean_checks: pd.DataFrame,
                       scores: pd.DataFrame, dq_overall: tuple[float, float]) -> None:
    sc = scores.pivot_table(index="table", columns="layer", values="dq_score").reset_index()[["table", "raw", "clean"]]
    failing = raw_checks[(raw_checks["failed_rows"] > 0) & ~raw_checks["check"].str.contains("info")]
    remaining = clean_checks[(clean_checks["failed_rows"] > 0) & ~clean_checks["check"].str.contains("info")]
    iss = issues[issues["rows_affected"] > 0]
    txt = f"""# Data Quality Report

> Auto-generated by `run_pipeline.py`. The dataset is **synthetic**: defects were deliberately injected into the
> RAW layer (`python/ingestion/generate_synthetic_data.py → inject_quality_issues`) to mirror problems typically
> seen in real retail source systems.

## 1. Approach

1. **Profiling** (`python/validation/profiling.py`): per-column missing %, distinct values, whitespace, numeric/date parse failures.
   Output: `data/outputs/data_quality/profile_raw.csv`.
2. **Rule-based checks** (`python/validation/quality_checks.py`): {len(raw_checks)} checks in 5 dimensions
   (Completeness, Uniqueness, Validity, Consistency, Integrity), run on **raw** and again on **clean** data.
3. **Cleaning** (`python/cleaning/cleaner.py`): every fix is logged with the number of rows affected.
4. **Scoring:** table score = mean pass-rate of its dimension scores. Overall = mean of table scores.
   Extreme outliers (3×IQR) are reported as *information only*: big Electronics baskets are real behaviour, not errors.

## 2. Score: Raw vs Clean (overall {dq_overall[0]:.2f} → {dq_overall[1]:.2f})

{md_table(sc)}
## 3. Issue Log: what was wrong, why, how detected, how fixed

{md_table(iss, ['table', 'issue', 'why_it_is_wrong', 'how_detected', 'how_fixed', 'rows_affected'], {'rows_affected': lambda v: f"{int(v):,}"})}
## 4. Failing checks in RAW layer ({len(failing)})

{md_table(failing, ['table', 'dimension', 'check', 'column', 'failed_rows', 'pass_rate'], {'failed_rows': lambda v: f"{int(v):,}"})}
## 5. Remaining exceptions after cleaning ({len(remaining)}), accepted by design

{md_table(remaining, ['table', 'dimension', 'check', 'column', 'failed_rows', 'pass_rate'], {'failed_rows': lambda v: f"{int(v):,}"})}
Why these remain:
- **email / signup_date nulls:** the true value is unknown, so it is not invented. Signup is imputed from the first order only where the customer has orders.
- **gender 'Not Specified', payment 'Unknown', priority 'Unassigned', return reason 'Not Specified', channel 'Unknown':**
  explicit unknown labels replace NULLs, so they are visible in reports instead of disappearing.
- **Unknown customer/product members (C_UNKNOWN / P_UNKNOWN):** orphan keys keep their revenue
  (standard data-warehouse practice) instead of silently dropping sales.
- **return_date nulls:** the date was before delivery, which is impossible. The return is still counted but the date is not trusted.

## 6. Reconciliation

- Unrepairable records are not deleted silently. They are written to `data/processed/quarantine/`.
- SQL equivalents of the checks live in `sql/04_data_quality.sql`, and SQL cleaning logic in `sql/05_cleaning.sql`.
"""
    (DOCS_DIR / "data_quality.md").write_text(txt, encoding="utf-8")
    log.info("Wrote docs/data_quality.md")
